#!/bin/bash

mkdir -p ~/.vim/autoload
curl --insecure -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim

# setup vimrc
ln -sf $(pwd)/vimrc ~/.vimrc

vim +PlugInstall +qall
